### ISSUE TITLE
wrong lua-tea branch

### ISSUE THREAD

**Issue by synodriver** [pk5ls20/wireshark_ntqq_protocol_plugin#2]
prealloc分支的那个使用了rand填充，不过显然马某的并没有填rand，他们是直接填0。理论上这可能有安全隐患，不过目前还是照做吧，用dev分支那个可能更好些，编译的时候加个```TEA_NORAND```就可以控制这种行为了

**Comment by pk5ls20** [comment]
> prealloc分支的那个使用了rand填充，不过显然马某的并没有填rand，他们是直接填0。理论上这可能有安全隐患，不过目前还是照做吧，用dev分支那个可能更好些，编译的时候加个`TEA_NORAND`就可以控制这种行为了

感谢，将在下个commit中使用
